### ISSUE TITLE
Usability Enhancements

### ISSUE THREAD

**Issue by vapvarun** [wbcomdesigns/buddypress-member-blog#18]
# BuddyPress Member Blog - Usability Enhancements

This document outlines implementation tasks for enhancing the usability of the BuddyPress Member Blog plugin, focusing on features that will make content creation more intuitive and engaging for community members.

## 1. Custom Formatting Toolbar

**Goal:** Create a simplified, user-friendly formatting toolbar with just the essential options.

### Implementation Tasks:

1. Create a filter for the TinyMCE initialization:

```php
// Add to public/class-buddypress-member-blog-public.php

/**
 * Customize TinyMCE toolbar for blog post creation
 */
public function customize_editor_toolbar() {
    add_filter('tiny_mce_before_init', array($this, 'modify_tinymce_settings'));
    add_filter('teeny_mce_before_init', array($this, 'modify_tinymce_settings'));
}

/**
 * Modify TinyMCE settings to simplify the toolbar
 * 
 * @param array $settings TinyMCE settings
 * @return array Modified settings
 */
public function modify_tinymce_settings($settings) {
    // Only modify on our post form
    if (!$this->is_member_blog_page()) {
        return $settings;
    }
    
    // Simplified first toolbar with essential formatting options
    $settings['toolbar1'] = 'formatselect,bold,italic,underline,bullist,numlist,link,unlink,undo,redo,fullscreen';
    
    // Remove second toolbar completely for simplicity
    $settings['toolbar2'] = '';
    
    // Limit available block formats to the most useful ones
    $settings['block_formats'] = 'Paragraph=p;Heading 2=h2;Heading 3=h3;Heading 4=h4';
    
    return $settings;
}

/**
 * Check if we're on a member blog page
 * 
 * @return bool
 */
private function is_member_blog_page() {
    global $post;
    $bp_member_blog_gen_stngs = get_option('bp_member_blog_gen_stngs');
    $blog_slug = apply_filters('bp_member_change_blog_slug', 'blog');
    
    return (
        is_a($post, 'WP_Post') && has_shortcode($post->post_content, 'bp-member-blog') ||
        (isset($bp_member_blog_gen_stngs['bp_post_page']) && is_page($bp_member_blog_gen_stngs['bp_post_page'])) ||
        bp_is_current_component($blog_slug)
    );
}

/**
 * Add hooks in constructor
 */
public function __construct($plugin_name, $version) {
    $this->plugin_name = $plugin_name;
    $this->version = $version;
    
    // Existing hooks...
    
    // Add custom toolbar
    add_action('init', array($this, 'customize_editor_toolbar'));
}
```

2. Add custom editor styles for the simplified toolbar:

```css
/* Add to public/css/buddypress-member-blog-public.css */

/* Custom styling for the simplified editor */
.bp-member-blog-container .wp-editor-container {
    border-radius: 4px;
    border: 1px solid #ddd;
}

.bp-member-blog-container .wp-editor-tools {
    background: #f9f9f9;
    padding: 8px;
    border-radius: 4px 4px 0 0;
}

.bp-member-blog-container .mce-toolbar .mce-btn button {
    padding: 4px;
}

.bp-member-blog-container .mce-toolbar .mce-btn.mce-active button {
    background: #eaeaea;
}

.bp-member-blog-container .wp-editor-area {
    min-height: 250px;
    padding: 15px;
    font-size: 16px;
    line-height: 1.6;
}
```

## 2. Drag-and-Drop Image Upload

**Goal:** Allow users to simply drag images into the editor instead of using the media uploader.

### Implementation Tasks:

1. Create JavaScript for handling drag and drop uploads:

```javascript
// Create new file: assets/js/drag-drop-upload.js

(function($) {
    'use strict';
    
    /**
     * Handle drag and drop file uploads for the editor
     */
    function initDragDropUpload() {
        // Elements
        const $editor = $('#bp_member_blog_post_content');
        const $editorContainer = $editor.closest('.wp-editor-container');
        const $dropzone = $('<div class="bp-member-blog-dropzone"><span>' + BPMemberBlogUpload.dropzone_text + '</span></div>');
        
        // Add dropzone after editor
        $editorContainer.after($dropzone);
        
        // Drag events for visual feedback
        $editorContainer.add($dropzone).on('dragover', function(e) {
            e.preventDefault();
            e.stopPropagation();
            $dropzone.addClass('drag-over');
        });
        
        $editorContainer.add($dropzone).on('dragleave', function(e) {
            e.preventDefault();
            e.stopPropagation();
            $dropzone.removeClass('drag-over');
        });
        
        // Handle actual drops
        $editorContainer.add($dropzone).on('drop', function(e) {
            e.preventDefault();
            e.stopPropagation();
            $dropzone.removeClass('drag-over');
            
            // Get dropped files
            const files = e.originalEvent.dataTransfer.files;
            
            if (!files.length) return;
            
            // Process each image file
            for (let i = 0; i < files.length; i++) {
                const file = files[i];
                
                // Check if file is an image
                if (!file.type.match(/^image\//)) {
                    continue;
                }
                
                uploadImage(file);
            }
        });
        
        /**
         * Upload image via AJAX
         */
        function uploadImage(file) {
            // Create FormData
            const data = new FormData();
            data.append('action', 'bp_member_blog_upload_image');
            data.append('nonce', BPMemberBlogUpload.upload_nonce);
            data.append('image', file);
            
            // Show upload progress
            const $progress = $('<div class="bp-member-blog-upload-progress"><span class="filename">' + file.name + '</span><div class="progress-bar"><div class="progress"></div></div></div>');
            $dropzone.append($progress);
            
            // Send AJAX request
            $.ajax({
                url: BPMemberBlogUpload.ajax_url,
                type: 'POST',
                data: data,
                processData: false,
                contentType: false,
                xhr: function() {
                    const xhr = new window.XMLHttpRequest();
                    
                    // Progress tracking
                    xhr.upload.addEventListener('progress', function(e) {
                        if (e.lengthComputable) {
                            const percent = Math.round((e.loaded / e.total) * 100);
                            $progress.find('.progress').css('width', percent + '%');
                        }
                    }, false);
                    
                    return xhr;
                },
                success: function(response) {
                    // Handle successful upload
                    $progress.addClass('completed');
                    setTimeout(function() {
                        $progress.fadeOut(function() {
                            $(this).remove();
                        });
                    }, 2000);
                    
                    if (response.success && response.data.html) {
                        // Insert image HTML into editor
                        if (typeof tinyMCE !== 'undefined' && tinyMCE.activeEditor && !tinyMCE.activeEditor.isHidden()) {
                            tinyMCE.activeEditor.execCommand('mceInsertContent', false, response.data.html);
                        } else {
                            const $editor = $('#bp_member_blog_post_content');
                            $editor.val($editor.val() + response.data.html);
                        }
                    }
                },
                error: function() {
                    // Handle error
                    $progress.addClass('error');
                    $progress.find('.filename').after('<span class="upload-error">' + BPMemberBlogUpload.upload_error + '</span>');
                }
            });
        }
    }
    
    $(document).ready(function() {
        // Initialize drag and drop if we're on a post form
        if ($('#bp_member_blog_post_content').length) {
            initDragDropUpload();
        }
    });
    
})(jQuery);
```

2. Add the server-side AJAX handler:

```php
// Add to public/class-buddypress-member-blog-public.php

/**
 * Enqueue drag-and-drop upload scripts
 */
public function enqueue_drag_drop_scripts() {
    if (!$this->is_member_blog_page()) {
        return;
    }
    
    wp_enqueue_script(
        'bp-member-blog-drag-drop',
        BUDDYPRESS_MEMBER_BLOG_PLUGIN_URL . 'assets/js/drag-drop-upload.js',
        array('jquery'),
        $this->version,
        true
    );
    
    wp_localize_script(
        'bp-member-blog-drag-drop',
        'BPMemberBlogUpload',
        array(
            'dropzone_text' => __('Drop images here to upload', 'buddypress-member-blog'),
            'upload_error' => __('Error uploading image', 'buddypress-member-blog'),
            'upload_nonce' => wp_create_nonce('bp_member_blog_upload_image'),
            'ajax_url' => admin_url('admin-ajax.php')
        )
    );
}

/**
 * AJAX handler for image uploads
 */
public function ajax_image_upload() {
    // Check nonce
    if (!check_ajax_referer('bp_member_blog_upload_image', 'nonce', false)) {
        wp_send_json_error(array('message' => __('Security verification failed', 'buddypress-member-blog')));
    }
    
    // Check if user can upload files
    if (!current_user_can('upload_files')) {
        wp_send_json_error(array('message' => __('You do not have permission to upload files', 'buddypress-member-blog')));
    }
    
    // Check if image is present
    if (empty($_FILES['image'])) {
        wp_send_json_error(array('message' => __('No image was provided', 'buddypress-member-blog')));
    }
    
    // Validate image
    $file = $_FILES['image'];
    $allowed_types = array('image/jpeg', 'image/png', 'image/gif');
    
    if (!in_array($file['type'], $allowed_types)) {
        wp_send_json_error(array('message' => __('Invalid file type. Please upload a JPG, PNG, or GIF', 'buddypress-member-blog')));
    }
    
    // Upload and get image data
    require_once(ABSPATH . 'wp-admin/includes/image.php');
    require_once(ABSPATH . 'wp-admin/includes/file.php');
    require_once(ABSPATH . 'wp-admin/includes/media.php');
    
    $attachment_id = media_handle_upload('image', 0);
    
    if (is_wp_error($attachment_id)) {
        wp_send_json_error(array('message' => $attachment_id->get_error_message()));
    }
    
    // Get image HTML
    $attachment = get_post($attachment_id);
    $image_src = wp_get_attachment_image_src($attachment_id, 'large');
    
    $html = '<img src="' . esc_url($image_src[0]) . '" alt="' . esc_attr($attachment->post_title) . '" class="aligncenter size-large wp-image-' . $attachment_id . '" />';
    
    wp_send_json_success(array(
        'id' => $attachment_id,
        'url' => $image_src[0],
        'html' => $html
    ));
}

/**
 * Add hooks in constructor
 */
public function __construct($plugin_name, $version) {
    $this->plugin_name = $plugin_name;
    $this->version = $version;
    
    // Existing hooks...
    
    // Drag and drop upload
    add_action('wp_enqueue_scripts', array($this, 'enqueue_drag_drop_scripts'));
    add_action('wp_ajax_bp_member_blog_upload_image', array($this, 'ajax_image_upload'));
}
```

3. Add CSS for the dropzone:

```css
/* Add to public/css/buddypress-member-blog-public.css */

/* Drag and drop upload zone */
.bp-member-blog-dropzone {
    border: 2px dashed #ddd;
    padding: 20px;
    margin: 15px 0;
    text-align: center;
    border-radius: 4px;
    background: #f9f9f9;
    transition: all 0.3s ease;
}

.bp-member-blog-dropzone.drag-over {
    background: #e9f7fe;
    border-color: #2271b1;
}

.bp-member-blog-dropzone span {
    color: #666;
    font-size: 14px;
}

/* Upload progress */
.bp-member-blog-upload-progress {
    margin: 10px 0;
    padding: 5px;
    background: #f0f0f0;
    border-radius: 4px;
    font-size: 12px;
}

.bp-member-blog-upload-progress .filename {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

.bp-member-blog-upload-progress .progress-bar {
    height: 5px;
    background: #ddd;
    border-radius: 3px;
    overflow: hidden;
}

.bp-member-blog-upload-progress .progress {
    height: 100%;
    background: #2271b1;
    width: 0;
    transition: width 0.3s ease;
}

.bp-member-blog-upload-progress.completed .progress {
    background: #46b450;
}

.bp-member-blog-upload-progress.error .progress {
    background: #dc3232;
}

.bp-member-blog-upload-progress .upload-error {
    color: #dc3232;
    margin-left: 10px;
}
```

## 3. @ Mentions Support

**Goal:** Allow mentioning other community members within blog posts to notify them.

### Implementation Tasks:

1. Add support for the BuddyPress mentions feature:

```php
// Add to public/class-buddypress-member-blog-public.php

/**
 * Enable BuddyPress @mentions in blog posts
 */
public function enable_mentions() {
    if (!$this->is_member_blog_page()) {
        return;
    }
    
    // Check if BuddyPress Mentions component is active
    if (!bp_is_active('mentions')) {
        return;
    }
    
    // Add the BP mentions scripts and autosuggest
    add_filter('bp_tinymce_enable_at_mention', '__return_true');
    
    // Load the mentions scripts
    bp_core_enqueue_mentions_script();
    
    // Add our own mentions handling script
    wp_enqueue_script(
        'bp-member-blog-mentions',
        BUDDYPRESS_MEMBER_BLOG_PLUGIN_URL . 'assets/js/mentions.js',
        array('jquery', 'bp-mentions'),
        $this->version,
        true
    );
}

/**
 * Process mentions when a post is published
 *
 * @param int $post_id The post ID
 */
public function process_mentions($post_id) {
    $post = get_post($post_id);
    
    if (!$post || $post->post_type !== 'post' || $post->post_status !== 'publish') {
        return;
    }
    
    // Extract mentions from content using BuddyPress function if available
    if (function_exists('bp_activity_find_mentions')) {
        $usernames = bp_activity_find_mentions(array('content' => $post->post_content));
    } else {
        // Fallback to regex if BuddyPress function isn't available
        $pattern = '/@([a-zA-Z0-9-_\.]+)/';
        preg_match_all($pattern, $post->post_content, $matches);
        $usernames = !empty($matches[1]) ? $matches[1] : array();
    }
    
    if (empty($usernames)) {
        return;
    }
    
    foreach ($usernames as $username) {
        $user = get_user_by('login', $username);
        
        if (!$user) {
            continue;
        }
        
        // Skip if the mentioned user is the author
        if ($user->ID === (int) $post->post_author) {
            continue;
        }
        
        // Create a BuddyPress notification
        if (function_exists('bp_notifications_add_notification')) {
            bp_notifications_add_notification(array(
                'user_id'           => $user->ID,
                'item_id'           => $post_id,
                'secondary_item_id' => $post->post_author,
                'component_name'    => 'bp_member_blog',
                'component_action'  => 'bp_member_blog_mention',
                'date_notified'     => bp_core_current_time(),
                'is_new'            => 1,
            ));
        }
        
        // Create an activity item for the mention
        if (function_exists('bp_activity_add')) {
            $activity_args = array(
                'user_id'       => $post->post_author,
                'action'        => sprintf(
                    __('%1$s mentioned %2$s in a blog post', 'buddypress-member-blog'),
                    bp_core_get_userlink($post->post_author),
                    bp_core_get_userlink($user->ID)
                ),
                'content'       => sprintf(
                    __('%1$s mentioned %2$s in the blog post <a href="%3$s">%4$s</a>', 'buddypress-member-blog'),
                    bp_core_get_userlink($post->post_author),
                    bp_core_get_userlink($user->ID),
                    get_permalink($post_id),
                    $post->post_title
                ),
                'component'     => 'bp_member_blog',
                'type'          => 'bp_member_blog_mention',
                'item_id'       => $post_id,
                'secondary_item_id' => $user->ID,
            );
            
            bp_activity_add($activity_args);
        }
    }
}

/**
 * Register notification type for mentions
 */
public function register_mention_notification() {
    // Register the notification type
    bp_notifications_register_notification_type(
        'bp_member_blog_mention',
        __('Blog post mentions', 'buddypress-member-blog'),
        __('Someone mentions you in a blog post', 'buddypress-member-blog'),
        'mentions'
    );
}

/**
 * Format the notification for mentions
 * 
 * @param string $action The notification action
 * @param int $item_id The notification item ID
 * @param int $secondary_item_id The notification secondary item ID
 * @param int $total_items The total number of notifications
 * @param string $format The format to return (string or array)
 * @return string|array Formatted notification
 */
public function format_mention_notification($action, $item_id, $secondary_item_id, $total_items, $format = 'string') {
    // Only handle our notification type
    if ($action !== 'bp_member_blog_mention') {
        return $action;
    }
    
    $post = get_post($item_id);
    
    if (!$post) {
        return $action;
    }
    
    $post_author = get_userdata($secondary_item_id);
    $post_title = $post->post_title;
    $post_link = get_permalink($post->ID);
    
    if ('string' === $format) {
        // Format for string notifications
        $return = sprintf(
            __('%s mentioned you in a blog post: %s', 'buddypress-member-blog'),
            $post_author->display_name,
            '<a href="' . esc_url($post_link) . '">' . esc_html($post_title) . '</a>'
        );
    } else {
        // Format for array notifications
        $return = array(
            'text' => sprintf(
                __('%s mentioned you in a blog post', 'buddypress-member-blog'),
                $post_author->display_name
            ),
            'link' => $post_link
        );
    }
    
    return $return;
}

/**
 * Add hooks in constructor
 */
public function __construct($plugin_name, $version) {
    $this->plugin_name = $plugin_name;
    $this->version = $version;
    
    // Existing hooks...
    
    // @ mentions support
    add_action('wp_enqueue_scripts', array($this, 'enable_mentions'));
    add_action('buddypress_member_blog_post_submit', array($this, 'process_mentions'));
    add_action('bp_init', array($this, 'register_mention_notification'));
    add_filter('bp_notifications_get_notifications_for_user', array($this, 'format_mention_notification'), 10, 5);
}
```

2. Create a JavaScript file for mentions handling:

```javascript
// Create new file: assets/js/mentions.js

(function($) {
    'use strict';
    
    /**
     * Initialize mentions in the editor
     */
    function initMentions() {
        // Wait for TinyMCE to load
        if (typeof tinyMCE === 'undefined' || !tinyMCE.activeEditor) {
            setTimeout(initMentions, 500);
            return;
        }
        
        const editor = tinyMCE.activeEditor;
        
        // Add atwho functionality to tinymce
        if (editor && !editor.isHidden() && typeof $.fn.atwho !== 'undefined') {
            $(editor.contentDocument.body).atwho({
                at: "@",
                data: ajaxurl + '?action=bp_get_suggestions&term=',
                displayTpl: "<li data-value='@${name}'>${image} ${name}</li>",
                limit: 10,
                callbacks: {
                    remote_filter: function(query, callback) {
                        $.getJSON(ajaxurl, {
                            action: 'bp_get_suggestions',
                            term: query,
                            type: 'members'
                        }, function(data) {
                            callback(data);
                        });
                    }
                }
            });
        }
        
        // Also add to the textarea for when TinyMCE is disabled
        const $textarea = $('#bp_member_blog_post_content');
        
        if ($textarea.length && typeof $.fn.atwho !== 'undefined') {
            $textarea.atwho({
                at: "@",
                data: ajaxurl + '?action=bp_get_suggestions&term=',
                displayTpl: "<li data-value='@${name}'>${image} ${name}</li>",
                limit: 10,
                callbacks: {
                    remote_filter: function(query, callback) {
                        $.getJSON(ajaxurl, {
                            action: 'bp_get_suggestions',
                            term: query,
                            type: 'members'
                        }, function(data) {
                            callback(data);
                        });
                    }
                }
            });
        }
    }
    
    $(document).ready(function() {
        // Initialize mentions
        if ($('#bp_member_blog_post_content').length) {
            initMentions();
        }
    });
    
})(jQuery);
```

## 4. Mobile-Optimized Editing

**Goal:** Enhance the mobile interface for creating content on smartphones and tablets.

### Implementation Tasks:

1. Add responsive styles for the editor:

```css
/* Add to public/css/buddypress-member-blog-public.css */

/* Mobile-optimized editor styles */
@media screen and (max-width: 782px) {
    /* Form container */
    .bp-member-blog-container {
        padding: 0;
    }
    
    .bp-member-blog-post-form {
        margin: 0;
        width: 100%;
    }
    
    /* Form fields */
    .bp-member-blog-field-container {
        margin-bottom: 20px;
    }
    
    .bp-member-blog-field-container label span {
        display: block;
        margin-bottom: 8px;
        font-size: 16px;
        font-weight: 600;
    }
    
    .bp-member-blog-field-container input[type="text"],
    .bp-member-blog-field-container select {
        width: 100%;
        height: 44px;
        font-size: 16px; /* Prevent iOS zoom on focus */
        padding: 8px 12px;
    }
    
    /* Editor */
    .wp-editor-tabs {
        display: flex;
    }
    
    .wp-editor-tabs button {
        flex: 1;
        height: 44px;
    }
    
    .wp-editor-container {
        border-radius: 4px;
    }
    
    .wp-editor-area {
        min-height: 200px;
        padding: 15px;
        font-size: 16px;
    }
    
    /* TinyMCE toolbar */
    .mce-toolbar-grp {
        padding: 2px;
    }
    
    .mce-toolbar .mce-btn {
        margin: 2px;
    }
    
    .mce-toolbar .mce-btn button {
        padding: 6px;
    }
    
    /* Categories and tags */
    .select2-container {
        width: 100% !important;
    }
    
    .select2-selection--multiple {
        min-height: 44px;
    }
    
    .select2-search__field {
        font-size: 16px;
    }
    
    /* Featured image upload */
    .bp-member-blog-featured-image-wrapper {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    
    .custom-file-upload {
        width: 100%;
        height: 44px;
        font-size: 16px;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    
    .bp_member_blog_post_img_preview {
        margin-top: 15px;
        text-align: center;
    }
    
    #bp_member_post_img_preview {
        max-width: 100%;
        height: auto;
    }
    
    /* Submit buttons */
    .bp-member-blog-submit-container {
        position: sticky;
        bottom: 0;
        background: #fff;
        padding: 10px;
        border-top: 1px solid #ddd;
        z-index: 100;
        margin: 20px -15px 0;
        display: flex;
    }
    
    .bp-member-blog-btn {
        flex: 1;
        margin: 0 5px;
        min-height: 44px;
        font-size: 16px;
    }
}

/* Medium-sized devices */
@media screen and (min-width: 783px) and (max-width: 1024px) {
    .bp-member-blog-container {
        padding: 15px;
    }
    
    .bp-member-blog-field-container label span {
        font-size: 15px;
    }
    
    .wp-editor-area {
        min-height: 250px;
    }
}
```

2. Add JavaScript to enhance the mobile experience:

```javascript
// Create new file: assets/js/mobile-editor.js

(function($) {
    'use strict';
    
    /**
     * Initialize mobile-optimized editing features
     */
    function initMobileOptimizations() {
        // Only apply on mobile devices
        if (window.innerWidth > 782) {
            return;
        }
        
        // Add mobile-specific class to the container
        $('.bp-member-blog-container').addClass('mobile-view');
        
        // Make editor toolbar sticky on scroll
        makeStickyToolbar();
        
        // Improve select2 usability on mobile
        improveSelect2Mobile();
        
        // Add tap-to-expand for categories and tags
        addTapToExpand();
    }
    
    /**
     * Make the editor toolbar sticky when scrolling
     */
    function makeStickyToolbar() {
        const $container = $('.bp-member-blog-container');
        const $editorToolbar = $('.mce-toolbar-grp');
        
        // Skip if no toolbar found
        if (!$editorToolbar.length) {
            return;
        }
        
        // Create a placeholder for the toolbar
        const $placeholder = $('<div class="mce-toolbar-placeholder"></div>').css('height', $editorToolbar.outerHeight());
        $placeholder.insertAfter($editorToolbar);
        $placeholder.hide();
        
        // Sticky functionality on scroll
        $(window).on('scroll', function() {
            const scrollTop = $(window).scrollTop();
            const toolbarOffset = $container.offset().top;
            
            if (scrollTop > toolbarOffset) {
                if (!$editorToolbar.hasClass('sticky')) {
                    $editorToolbar.addClass('sticky').css({
                        'position': 'fixed',
                        'top': '0',
                        'width': $container.width() + 'px',
                        'z-index': '100',
                        'background': '#fff',
                        'border-bottom': '1px solid #ddd'
                    });
                    $placeholder.show();
                }
            } else {
                $editorToolbar.removeClass('sticky').css({
                    'position': '',
                    'top': '',
                    'width': '',
                    'z-index': '',
                    'background': '',
                    'border-bottom': ''
                });
                $placeholder.hide();
            }
        });
        
        // Update toolbar width on resize
        $(window).on('resize', function() {
            if ($editorToolbar.hasClass('sticky')) {
                $editorToolbar.css('width', $container.width() + 'px');
            }
        });
    }
    
    /**
     * Improve Select2 usability on mobile devices
     */
    function improveSelect2Mobile() {
        // Increase touchable area for select2 elements
        $('.select2-selection__choice__remove').css({
            'padding': '5px 10px',
            'margin-right': '-8px'
        });
        
        // Keep dropdown open on scroll
        $('.select2-container').on('touchstart', function(e) {
            e.stopPropagation();
        });
    }
    
    /**
     * Add tap-to-expand functionality for form sections
     */
    function addTapToExpand() {
        // Add toggle indicators to form section headings
        $('.bp-member-blog-field-container label > span').each(function() {
            $(this).append('<i class="toggle-indicator"></i>');
        });
        
        // Categories and tags expand/collapse
        $('.bp-member-blog-field-container label > span').on('click', function() {
            const $label = $(this).closest('label');
            const $content = $label.find('.bp-member-blog-post-category-wrapper, .bpmb-post-tag-lists');
            
            if ($content.length) {
                $content.slideToggle(200);
                $label.toggleClass('expanded');
            }
        });
    }
    
    $(document).ready(function() {
        // Initialize mobile optimizations
        initMobileOptimizations();
        
        // Re-initialize on orientation change
        $(window).on('orientationchange', function() {
            setTimeout(initMobileOptimizations, 200);
        });
    });
    
})(jQuery);
```

3. Enqueue the mobile optimization script:

```php
// Add to public/class-buddypress-member-blog-public.php

/**
 * Enqueue mobile optimization scripts
 */
public function enqueue_mobile_scripts() {
    if (!$this->is_member_blog_page()) {
        return;
    }
    
    wp_enqueue_script(
        'bp-member-blog-mobile',
        BUDDYPRESS_MEMBER_BLOG_PLUGIN_URL . 'assets/js/mobile-editor.js',
        array('jquery'),
        $this->version,
        true
    );
    
    // Add viewport meta tag for proper mobile rendering if not already present
    add_action('wp_head', array($this, 'add_viewport_meta'));
}

/**
 * Add viewport meta tag
 */
public function add_viewport_meta() {
    echo '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">' . "\n";
}

/**
 * Add hooks in constructor
 */
public function __construct($plugin_name, $version) {
    $this->plugin_name = $plugin_name;
    $this->version = $version;
    
    // Existing hooks...
    
    // Mobile optimizations
    add_action('wp_enqueue_scripts', array($this, 'enqueue_mobile_scripts'));
}
```

## Integration Tasks

To integrate all these features, ensure the following steps are completed:

1. Create necessary JavaScript files:
   - `assets/js/drag-drop-upload.js`
   - `assets/js/mentions.js`
   - `assets/js/mobile-editor.js`

2. Update CSS in `public/css/buddypress-member-blog-public.css` with all the new styles

3. Add all hooks in the constructor of `public/class-buddypress-member-blog-public.php`

4. Update the template files to support the new features:
   - Update `templates/edit.php` to accommodate mobile view
   - Ensure proper ARIA attributes are applied throughout for accessibility

5. Test the implementation on:
   - Desktop browsers
   - Mobile browsers (iOS and Android)
   - With different BuddyPress themes

## Recommended Implementation Schedule

1. **Phase 1**: Implement the Custom Formatting Toolbar
   - This has minimal dependencies and provides immediate UX improvements

2. **Phase 2**: Add Mobile-Optimized Editing
   - This enhances usability for a significant portion of users

3. **Phase 3**: Implement Drag-and-Drop Image Upload
   - This requires more extensive testing but offers significant usability improvement

4. **Phase 4**: Integrate @ Mentions Support
   - This requires BuddyPress Mentions component and adds social features
